# Generated by Django 4.0.4 on 2022-06-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_hrac_options_alter_klub_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrac',
            name='popis',
            field=models.CharField(blank=True, max_length=300, verbose_name='Popis hráče'),
        ),
    ]
