# Generated by Django 4.0.4 on 2022-06-05 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_hrac_popis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrac',
            name='popis',
        ),
        migrations.AddField(
            model_name='hrac',
            name='poradi_zlaty_mic',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Pořadí (zlatý míč)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hrac',
            name='pozice',
            field=models.CharField(choices=[('útočník', 'útočník'), ('záložník', 'záložník'), ('obránce', 'obránce'), ('brankář', 'brankář')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hrac',
            name='preferovana_noha',
            field=models.CharField(choices=[('pravá', 'pravá'), ('levá', 'levá')], max_length=50, verbose_name='Preferovaná noha'),
        ),
    ]
